mydata <- read.csv("Data Analysis Project/household_power_consumption.txt", header = TRUE,sep = ";")
mydata$datetime <- strptime(paste(mydata$Date,mydata$Time), format = "%d/%m/%Y %H:%M:%S")
mydata$Date <- as.character(mydata$Date)
reqdata <- subset(mydata, (Date=="1/2/2007" | Date=="2/2/2007"))
reqdata$Global_active_power<- as.character(reqdata$Global_active_power)
reqdata$Global_active_power<- as.numeric(reqdata$Global_active_power)
#reqdata$datetime <- strptime(paste(reqdata$Date,reqdata$Time), format = "%d/%m/%Y %H:%M:%S")
Sys.setlocale("LC_ALL","English")
reqdata$Sub_metering_1 <- as.character(reqdata$Sub_metering_1)
reqdata$Sub_metering_1 <- as.numeric(reqdata$Sub_metering_1)
reqdata$Sub_metering_2 <- as.character(reqdata$Sub_metering_2)
reqdata$Sub_metering_2 <- as.numeric(reqdata$Sub_metering_2)
reqdata$Sub_metering_3 <- as.character(reqdata$Sub_metering_3)
reqdata$Sub_metering_3 <- as.numeric(reqdata$Sub_metering_3)
with(reqdata, plot(datetime,Sub_metering_1,type="l",col="black",xlab = "",ylab = "Energy sub metering"))
lines(reqdata$datetime,reqdata$Sub_metering_2,col="red")
lines(reqdata$datetime,reqdata$Sub_metering_3,col="blue")
legend("topright",pch = "_",col = c("black","red","blue"),legend = c("sub_metering_1","sub_metering_2","sub_metering_3"), cex=0.75)
dev.copy(png,file="Plot3.png")
dev.off()