mydata <- read.csv("Data Analysis Project/household_power_consumption.txt", header = TRUE,sep = ";")
mydata$datetime <- strptime(paste(mydata$Date,mydata$Time), format = "%d/%m/%Y %H:%M:%S")
mydata$Date <- as.character(mydata$Date)
reqdata <- subset(mydata, (Date=="1/2/2007" | Date=="2/2/2007"))
reqdata$Global_active_power<- as.character(reqdata$Global_active_power)
reqdata$Global_active_power<- as.numeric(reqdata$Global_active_power)
Sys.setlocale("LC_ALL","English")
reqdata$Sub_metering_1 <- as.character(reqdata$Sub_metering_1)
reqdata$Sub_metering_1 <- as.numeric(reqdata$Sub_metering_1)
reqdata$Sub_metering_2 <- as.character(reqdata$Sub_metering_2)
reqdata$Sub_metering_2 <- as.numeric(reqdata$Sub_metering_2)
reqdata$Sub_metering_3 <- as.character(reqdata$Sub_metering_3)
reqdata$Sub_metering_3 <- as.numeric(reqdata$Sub_metering_3)
reqdata$Voltage <- as.character(reqdata$Voltage)
reqdata$Voltage <- as.numeric(reqdata$Voltage)
reqdata$Global_reactive_power <- as.character(reqdata$Global_reactive_power)
reqdata$Global_reactive_power <- as.numeric(reqdata$Global_reactive_power)
par(mfrow=c(2,2),mar=c(4,4,2,1),oma=c(0,0,2,0))
with(reqdata,{
        plot(datetime,Global_active_power,ylab = "Global Active Power (kilowatts)",xlab = "",type = "l")
        plot(datetime,Voltage, type = "l")
        plot(datetime,Sub_metering_1,type="l",col="black",xlab = "",ylab = "Energy sub metering")
        lines(reqdata$datetime,reqdata$Sub_metering_2,col="red")
        lines(reqdata$datetime,reqdata$Sub_metering_3,col="blue")
        legend("topright",bty = "n",pch = "__",col = c("black","red","blue"),legend = c("sub_metering_1","sub_metering_2","sub_metering_3"),cex=0.5)
        plot(datetime, Global_reactive_power, type = "l")
        })
dev.copy(png,file="Plot4.png")
dev.off()