mydata <- read.csv("Data Analysis Project/household_power_consumption.txt", header = TRUE,sep = ";")
mydata$datetime <- strptime(paste(mydata$Date,mydata$Time), format = "%d/%m/%Y %H:%M:%S")
mydata$Date <- as.character(mydata$Date)
reqdata <- subset(mydata, (Date=="1/2/2007" | Date=="2/2/2007"))
reqdata$Global_active_power<- as.character(reqdata$Global_active_power)
reqdata$Global_active_power<- as.numeric(reqdata$Global_active_power)
#reqdata$datetime <- strptime(paste(reqdata$Date,reqdata$Time), format = "%d/%m/%Y %H:%M:%S")
Sys.setlocale("LC_ALL","English")
png(filename = "Plot2.png",width = 480,height = 480)
with(reqdata, plot(datetime,Global_active_power,ylab = "Global Active Power (kilowatts)",xlab = "",type = "l"))
dev.off()