library(lubridate)
mydata <- read.csv("Data Analysis Project/household_power_consumption.txt", header = TRUE,sep = ";")
mydata$Date <- as.character(mydata$Date)
reqdata <- subset(mydata, (Date=="1/2/2007" | Date=="2/2/2007"))
reqdata$Date <- dmy(reqdata$Date)
reqdata$Global_active_power <- as.character(reqdata$Global_active_power)
reqdata$Global_active_power <- as.numeric(reqdata$Global_active_power)
png(filename = "Plot1.png",width = 480,height = 480)
hist(reqdata$Global_active_power, col = "red", xlab = "Global Active Power (kilowatts)", main = "Global Active Power")
dev.off()